# -*- coding: utf-8 -*-
"""OKF (Open Knowledge Format) — three-layer concept system for knowledge base.

This module implements the OKF concept system inspired by StaffDeck,
replacing naive chunk slicing with structured knowledge representation:

1. **SourceDocument** — Document-level metadata card (title/source/summary)
2. **SourceSection** — Section-level (target ~1400 chars/section, max 80 sections),
   preserves page numbers and hierarchical position
3. **Bucket** — Cross-section task bucket, groups sections by query intent
   (bucket_key/title/summary/section_ids/applicable_query_types)

Storage: JSON + frontmatter (using QwenPaw's existing aiofiles + orjson pattern,
no database required).

Dual-route retrieval:
- **Concept route**: Navigate the OKF hierarchy (Document → Section → Bucket)
- **Bucket route**: Match query to bucket_key, then retrieve associated sections
- When ReMe embedding is available, it's layered on top for semantic recall.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..constant import WORKING_DIR

logger = logging.getLogger(__name__)

# OKF storage directory
OKF_DIR = WORKING_DIR / "knowledge" / "okf"

# Target section size in characters
TARGET_SECTION_CHARS = 1400
MAX_SECTIONS_PER_DOC = 80


# ---------------------------------------------------------------------------
# OKF Data Models
# ---------------------------------------------------------------------------

@dataclass
class SourceDocument:
    """Document-level metadata card.

    Attributes:
        doc_id: Unique document ID (SHA-256 of content, first 16 chars).
        title: Document title.
        source: File path or URL.
        summary: Auto-generated summary.
        file_type: pdf / docx / md / txt ...
        page_count: Number of pages (if known).
        section_count: Number of sections extracted.
        created_at: ISO 8601 timestamp.
        metadata: Extra metadata (author, date, tags, etc.).
    """

    doc_id: str = ""
    title: str = ""
    source: str = ""
    summary: str = ""
    file_type: str = ""
    page_count: int = 0
    section_count: int = 0
    created_at: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SourceDocument":
        return cls(**{k: data.get(k) for k in cls.__dataclass_fields__})

    def to_frontmatter(self) -> str:
        """Serialize as YAML frontmatter for Markdown storage."""
        lines = ["---"]
        lines.append(f"doc_id: {self.doc_id}")
        lines.append(f"title: {self.title}")
        lines.append(f"source: {self.source}")
        lines.append(f"file_type: {self.file_type}")
        lines.append(f"page_count: {self.page_count}")
        lines.append(f"section_count: {self.section_count}")
        lines.append(f"created_at: {self.created_at}")
        if self.summary:
            # Escape newlines for YAML
            summary = self.summary.replace("\n", " ").replace('"', '\\"')
            lines.append(f'summary: "{summary}"')
        for k, v in self.metadata.items():
            lines.append(f"{k}: {v}")
        lines.append("---")
        return "\n".join(lines)


@dataclass
class SourceSection:
    """Section-level knowledge unit.

    Attributes:
        section_id: Unique section ID (doc_id + sequence number).
        doc_id: Parent document ID.
        sequence: 0-based section index within the document.
        title: Section heading (if extracted from the document).
        content: Section text content (~1400 chars target).
        page_start: Starting page number (if known).
        page_end: Ending page number.
        char_count: Character count of content.
        bucket_ids: IDs of buckets that reference this section.
    """

    section_id: str = ""
    doc_id: str = ""
    sequence: int = 0
    title: str = ""
    content: str = ""
    page_start: int = 0
    page_end: int = 0
    char_count: int = 0
    bucket_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SourceSection":
        return cls(**{k: data.get(k) for k in cls.__dataclass_fields__})


@dataclass
class Bucket:
    """Cross-section task bucket — groups sections by query intent.

    Buckets are generated by LLM to cluster sections that are relevant
    to the same type of query, even if they're in different parts of
    the document.

    Attributes:
        bucket_id: Unique bucket ID.
        bucket_key: Short identifier (e.g., "evidence_rules", "arbitration_procedure").
        title: Human-readable title.
        summary: What this bucket covers.
        section_ids: IDs of sections in this bucket.
        applicable_query_types: Types of queries this bucket answers
                                (e.g., ["factual", "procedural", "legal_basis"]).
        doc_id: Parent document ID.
    """

    bucket_id: str = ""
    bucket_key: str = ""
    title: str = ""
    summary: str = ""
    section_ids: list[str] = field(default_factory=list)
    applicable_query_types: list[str] = field(default_factory=list)
    doc_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Bucket":
        return cls(**{k: data.get(k) for k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# Document ingestion — split into sections
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _generate_doc_id(content: str) -> str:
    """Generate a document ID from content hash."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


def split_into_sections(
    content: str,
    doc_id: str,
    target_chars: int = TARGET_SECTION_CHARS,
    max_sections: int = MAX_SECTIONS_PER_DOC,
) -> list[SourceSection]:
    """Split document content into sections of approximately target_chars.

    Tries to split on heading boundaries first, then on paragraph breaks,
    finally falling back to character-based splitting.

    Args:
        content: Full document text.
        doc_id: Parent document ID.
        target_chars: Target characters per section.
        max_sections: Maximum number of sections to create.

    Returns:
        List of SourceSection objects.
    """
    if not content.strip():
        return []

    # Try to split on markdown headings (## or ###)
    heading_pattern = re.compile(r"^(#{1,4}\s+.+)$", re.MULTILINE)
    heading_positions = [m.start() for m in heading_pattern.finditer(content)]

    sections: list[SourceSection] = []

    if len(heading_positions) > 1:
        # Split by headings
        for i, pos in enumerate(heading_positions):
            if i >= max_sections:
                break
            end = heading_positions[i + 1] if i + 1 < len(heading_positions) else len(content)
            section_content = content[pos:end].strip()
            if not section_content:
                continue

            # Extract heading as title
            title_match = heading_pattern.match(section_content)
            title = title_match.group(1).lstrip("#").strip() if title_match else ""

            sections.append(SourceSection(
                section_id=f"{doc_id}_s{len(sections)}",
                doc_id=doc_id,
                sequence=len(sections),
                title=title,
                content=section_content,
                char_count=len(section_content),
            ))
    else:
        # Split by double newlines (paragraphs)
        paragraphs = re.split(r"\n\s*\n", content)
        current_chunk = ""
        for para in paragraphs:
            if len(current_chunk) + len(para) > target_chars and current_chunk:
                sections.append(SourceSection(
                    section_id=f"{doc_id}_s{len(sections)}",
                    doc_id=doc_id,
                    sequence=len(sections),
                    content=current_chunk.strip(),
                    char_count=len(current_chunk.strip()),
                ))
                current_chunk = para
            else:
                current_chunk = current_chunk + "\n\n" + para if current_chunk else para

            if len(sections) >= max_sections:
                break

        # Don't forget the last chunk
        if current_chunk.strip() and len(sections) < max_sections:
            sections.append(SourceSection(
                section_id=f"{doc_id}_s{len(sections)}",
                doc_id=doc_id,
                sequence=len(sections),
                content=current_chunk.strip(),
                char_count=len(current_chunk.strip()),
            ))

    return sections


def create_source_document(
    content: str,
    title: str = "",
    source: str = "",
    file_type: str = "",
    page_count: int = 0,
    metadata: dict[str, Any] | None = None,
) -> tuple[SourceDocument, list[SourceSection]]:
    """Create a SourceDocument and its sections from content.

    Args:
        content: Full document text.
        title: Document title.
        source: File path or URL.
        file_type: File extension.
        page_count: Number of pages.
        metadata: Extra metadata.

    Returns:
        Tuple of (SourceDocument, list of SourceSection).
    """
    doc_id = _generate_doc_id(content)
    sections = split_into_sections(content, doc_id)

    doc = SourceDocument(
        doc_id=doc_id,
        title=title or source or doc_id,
        source=source,
        file_type=file_type,
        page_count=page_count,
        section_count=len(sections),
        created_at=_now_iso(),
        metadata=metadata or {},
    )

    return doc, sections


# ---------------------------------------------------------------------------
# Storage — JSON file persistence
# ---------------------------------------------------------------------------

def _ensure_okf_dir(doc_id: str | None = None) -> Path:
    """Ensure OKF directory exists. If doc_id is given, ensure doc subdir."""
    if doc_id:
        path = OKF_DIR / doc_id
    else:
        path = OKF_DIR
    path.mkdir(parents=True, exist_ok=True)
    return path


def save_okf_document(
    doc: SourceDocument,
    sections: list[SourceSection],
    buckets: list[Bucket] | None = None,
) -> Path:
    """Save an OKF document and its sections/buckets to disk.

    Creates a directory structure:
        ~/.aiarb/knowledge/okf/<doc_id>/
            document.json
            sections.json
            buckets.json (if buckets provided)

    Returns the document directory path.
    """
    doc_dir = _ensure_okf_dir(doc.doc_id)

    # Save document metadata
    (doc_dir / "document.json").write_text(
        json.dumps(doc.to_dict(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # Save sections
    (doc_dir / "sections.json").write_text(
        json.dumps([s.to_dict() for s in sections], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # Save buckets (if provided)
    if buckets:
        (doc_dir / "buckets.json").write_text(
            json.dumps([b.to_dict() for b in buckets], indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    logger.info("Saved OKF document '%s' with %d sections", doc.doc_id, len(sections))
    return doc_dir


def load_okf_document(doc_id: str) -> tuple[SourceDocument, list[SourceSection], list[Bucket]] | None:
    """Load an OKF document by ID.

    Returns (document, sections, buckets) or None if not found.
    """
    doc_dir = OKF_DIR / doc_id
    if not doc_dir.is_dir():
        return None

    try:
        doc_data = json.loads((doc_dir / "document.json").read_text(encoding="utf-8"))
        doc = SourceDocument.from_dict(doc_data)

        sections_data = json.loads((doc_dir / "sections.json").read_text(encoding="utf-8"))
        sections = [SourceSection.from_dict(s) for s in sections_data]

        buckets = []
        buckets_path = doc_dir / "buckets.json"
        if buckets_path.exists():
            buckets_data = json.loads(buckets_path.read_text(encoding="utf-8"))
            buckets = [Bucket.from_dict(b) for b in buckets_data]

        return doc, sections, buckets
    except Exception as e:
        logger.error("Failed to load OKF document '%s': %s", doc_id, e)
        return None


def list_okf_documents() -> list[SourceDocument]:
    """List all OKF documents."""
    docs: list[SourceDocument] = []
    if not OKF_DIR.is_dir():
        return docs
    for doc_dir in sorted(OKF_DIR.iterdir()):
        if not doc_dir.is_dir():
            continue
        doc_path = doc_dir / "document.json"
        if doc_path.exists():
            try:
                data = json.loads(doc_path.read_text(encoding="utf-8"))
                docs.append(SourceDocument.from_dict(data))
            except Exception as e:
                logger.warning("Failed to load OKF doc from %s: %s", doc_dir, e)
    return docs


def delete_okf_document(doc_id: str) -> bool:
    """Delete an OKF document and all its sections/buckets."""
    import shutil
    doc_dir = OKF_DIR / doc_id
    if not doc_dir.is_dir():
        return False
    shutil.rmtree(doc_dir)
    logger.info("Deleted OKF document '%s'", doc_id)
    return True


# ---------------------------------------------------------------------------
# Dual-route retrieval
# ---------------------------------------------------------------------------

def search_by_concept(
    query: str,
    doc_id: str | None = None,
    top_k: int = 5,
) -> list[tuple[SourceSection, float]]:
    """Concept route: search sections by keyword matching.

    This is the lexical fallback when LLM/embedding is not available.
    Scores sections by keyword overlap with the query.

    Args:
        query: Search query.
        doc_id: Optional document ID to restrict search.
        top_k: Maximum number of results.

    Returns:
        List of (section, score) tuples, sorted by score descending.
    """
    results: list[tuple[SourceSection, float]] = []
    query_terms = set(query.lower().split())

    doc_ids = [doc_id] if doc_id else [d.doc_id for d in list_okf_documents()]

    for did in doc_ids:
        loaded = load_okf_document(did)
        if loaded is None:
            continue
        _, sections, _ = loaded

        for section in sections:
            content_lower = section.content.lower()
            title_lower = section.title.lower()
            text = title_lower + " " + content_lower

            # Simple TF scoring
            score = sum(1 for term in query_terms if term in text)
            if score > 0:
                # Normalize by content length
                score = score / (len(text) / 1000 + 1)
                results.append((section, score))

    results.sort(key=lambda x: x[1], reverse=True)
    return results[:top_k]


def search_by_bucket(
    query: str,
    doc_id: str | None = None,
    top_k: int = 5,
) -> list[tuple[SourceSection, float]]:
    """Bucket route: match query to buckets, then retrieve sections.

    If buckets exist for a document, match the query against bucket
    titles/summaries/keys, then return the sections in matching buckets.

    Args:
        query: Search query.
        doc_id: Optional document ID to restrict search.
        top_k: Maximum number of results.

    Returns:
        List of (section, score) tuples.
    """
    results: list[tuple[SourceSection, float]] = []
    query_lower = query.lower()

    doc_ids = [doc_id] if doc_id else [d.doc_id for d in list_okf_documents()]

    for did in doc_ids:
        loaded = load_okf_document(did)
        if loaded is None:
            continue
        _, sections, buckets = loaded

        if not buckets:
            # No buckets — fall back to concept search
            continue

        # Build section lookup
        section_map = {s.section_id: s for s in sections}

        # Match query against buckets
        for bucket in buckets:
            bucket_text = (bucket.title + " " + bucket.summary + " " + bucket.bucket_key).lower()
            bucket_terms = set(bucket_text.split())
            query_terms = set(query_lower.split())
            overlap = query_terms & bucket_terms

            if overlap:
                score = len(overlap) / (len(query_terms) + 1)
                for sid in bucket.section_ids:
                    section = section_map.get(sid)
                    if section:
                        results.append((section, score))

    results.sort(key=lambda x: x[1], reverse=True)
    return results[:top_k]


def dual_route_search(
    query: str,
    doc_id: str | None = None,
    top_k: int = 5,
) -> list[dict[str, Any]]:
    """Dual-route retrieval: try bucket route first, then concept route.

    Merges and deduplicates results from both routes.

    Args:
        query: Search query.
        doc_id: Optional document ID to restrict search.
        top_k: Maximum number of results.

    Returns:
        List of result dicts with section_id, doc_id, title, content,
        score, and route fields.
    """
    # Try bucket route first
    bucket_results = search_by_bucket(query, doc_id, top_k)

    # Then concept route
    concept_results = search_by_concept(query, doc_id, top_k)

    # Merge and deduplicate
    seen: set[str] = set()
    merged: list[dict[str, Any]] = []

    for section, score in bucket_results:
        if section.section_id not in seen:
            seen.add(section.section_id)
            merged.append({
                "section_id": section.section_id,
                "doc_id": section.doc_id,
                "title": section.title,
                "content": section.content[:500],  # Truncate for preview
                "score": score,
                "route": "bucket",
            })

    for section, score in concept_results:
        if section.section_id not in seen:
            seen.add(section.section_id)
            merged.append({
                "section_id": section.section_id,
                "doc_id": section.doc_id,
                "title": section.title,
                "content": section.content[:500],
                "score": score * 0.8,  # Slightly lower priority for concept route
                "route": "concept",
            })

    merged.sort(key=lambda x: x["score"], reverse=True)
    return merged[:top_k]


# ---------------------------------------------------------------------------
# Bucket generation (LLM-powered, optional)
# ---------------------------------------------------------------------------

async def generate_buckets(
    doc: SourceDocument,
    sections: list[SourceSection],
    agent_id: str | None = None,
) -> list[Bucket]:
    """Generate cross-section task buckets using LLM.

    This is the OKF enhancement that groups sections by query intent.
    Uses model_factory to call the LLM with a bucketing prompt.

    Args:
        doc: The source document.
        sections: The document's sections.
        agent_id: Agent ID for model configuration.

    Returns:
        List of generated Bucket objects.
    """
    if not sections:
        return []

    try:
        from ..agents.model_factory import create_model_and_formatter
        from ..framework.message import Msg, TextBlock
        from ..utils.model_response import consume_model_response
    except ImportError as e:
        logger.warning("Cannot import model dependencies for bucket generation: %s", e)
        return []

    # Build section summaries for the prompt
    section_summaries = []
    for s in sections[:MAX_SECTIONS_PER_DOC]:
        preview = s.content[:200].replace("\n", " ")
        section_summaries.append(f"  - [{s.section_id}] {s.title}: {preview}")

    prompt = f"""\
Analyze the following document sections and create 3-8 task buckets that group
sections by the types of queries they can answer.

Document: {doc.title}
Sections:
{chr(10).join(section_summaries)}

Output a JSON array of bucket objects:
```json
[
  {{
    "bucket_key": "short_identifier",
    "title": "Human-readable title",
    "summary": "What queries this bucket answers",
    "section_ids": ["{sections[0].section_id if sections else ''}"],
    "applicable_query_types": ["factual", "procedural", "legal_basis"]
  }}
]
```

Rules:
1. Each section can appear in multiple buckets.
2. bucket_key should be lowercase with underscores.
3. applicable_query_types: factual, procedural, legal_basis, definitional, analytical
4. Output ONLY the JSON array, no explanation.
"""

    try:
        model, _ = create_model_and_formatter(agent_id=agent_id)
        messages = [
            Msg(
                name="system",
                role="system",
                content=[TextBlock(type="text", text="You generate JSON output for knowledge bucketing.")],
            ),
            Msg(
                name="user",
                role="user",
                content=[TextBlock(type="text", text=prompt)],
            ),
        ]
        raw = await consume_model_response(model, messages)

        # Parse JSON array
        import re
        match = re.search(r"\[.*\]", raw, re.DOTALL)
        if not match:
            logger.warning("No JSON array found in bucket generation response")
            return []

        bucket_data = json.loads(match.group(0))
        buckets = []
        for i, b in enumerate(bucket_data):
            buckets.append(Bucket(
                bucket_id=f"{doc.doc_id}_b{i}",
                doc_id=doc.doc_id,
                bucket_key=b.get("bucket_key", f"bucket_{i}"),
                title=b.get("title", ""),
                summary=b.get("summary", ""),
                section_ids=b.get("section_ids", []),
                applicable_query_types=b.get("applicable_query_types", []),
            ))

        # Update sections with bucket references
        for bucket in buckets:
            for sid in bucket.section_ids:
                for section in sections:
                    if section.section_id == sid:
                        if bucket.bucket_id not in section.bucket_ids:
                            section.bucket_ids.append(bucket.bucket_id)

        logger.info("Generated %d buckets for document '%s'", len(buckets), doc.doc_id)
        return buckets

    except Exception as e:
        logger.error("Bucket generation failed: %s", e)
        return []


# ---------------------------------------------------------------------------
# Citation formatting (simplified from StaffDeck's citations.py)
# ---------------------------------------------------------------------------

def format_citations(results: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Format search results as citation objects.

    Args:
        results: Output from dual_route_search().

    Returns:
        List of citation dicts with label, doc_id, section_id, and preview.
    """
    citations = []
    for i, result in enumerate(results):
        label = f"[{i+1}]"
        if result.get("title"):
            label += f" {result['title']}"
        citations.append({
            "label": label,
            "doc_id": result.get("doc_id", ""),
            "section_id": result.get("section_id", ""),
            "preview": result.get("content", "")[:200],
            "route": result.get("route", ""),
        })
    return citations
