version: '3.8'

volumes:
  aiarb-data:
    name: aiarb-data
  aiarb-secrets:
    name: aiarb-secrets
  aiarb-backups:
    name: aiarb-backups

services:
  aiarb:
    build:
      context: .
      dockerfile: deploy/Dockerfile.local
    container_name: aiarb
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - AIARB_AUTH_ENABLED=true
    #   - AIARB_AUTH_USERNAME=admin
    #   - AIARB_AUTH_PASSWORD=yourpassword
    volumes:
      - aiarb-data:/app/working
      - aiarb-secrets:/app/working.secret
      - aiarb-backups:/app/working.backups